# Generated by Django 6.0.5 on 2026-06-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="body_type",
            field=models.CharField(default="SUV", max_length=50),
        ),
        migrations.AddField(
            model_name="car",
            name="color",
            field=models.CharField(default="Black", max_length=50),
        ),
        migrations.AddField(
            model_name="car",
            name="engine_size",
            field=models.CharField(default="V6", max_length=50),
        ),
        migrations.AddField(
            model_name="car",
            name="fuel_type",
            field=models.CharField(default="Petrol", max_length=50),
        ),
        migrations.AddField(
            model_name="car",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="condition",
            field=models.CharField(
                choices=[
                    ("Brand New", "Brand New"),
                    ("Foreign Used", "Foreign Used"),
                    ("Local Used", "Local Used"),
                ],
                default="Foreign Used",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="mileage",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="car",
            name="transmission",
            field=models.CharField(
                choices=[("Automatic", "Automatic"), ("Manual", "Manual")],
                default="Automatic",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="year",
            field=models.PositiveIntegerField(default=2020),
        ),
    ]
