# Generated by Django 6.0.5 on 2026-05-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="car_photos/"),
        ),
    ]
