# Generated by Django 6.0.5 on 2026-05-10 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0002_car_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.ImageField(default=1, upload_to="cars/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="car",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="CarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="cars/gallery/")),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="showroom.car",
                    ),
                ),
            ],
        ),
    ]
