# Generated by Django 6.0.5 on 2026-06-14 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0002_car_body_type_car_color_car_engine_size_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("date", models.DateField()),
                (
                    "time_slot",
                    models.CharField(
                        choices=[
                            ("10:00", "10:00 AM"),
                            ("12:00", "12:00 PM"),
                            ("14:00", "02:00 PM"),
                            ("16:00", "04:00 PM"),
                        ],
                        max_length=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="showroom.car",
                    ),
                ),
            ],
            options={
                "unique_together": {("car", "date", "time_slot")},
            },
        ),
    ]
