# Generated by Django 6.0.5 on 2026-05-11 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "showroom",
            "0003_remove_car_created_at_alter_car_image_alter_car_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CarVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="cars/videos/")),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="showroom.car",
                    ),
                ),
            ],
        ),
    ]
