# Generated by Django 6.0.5 on 2026-06-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0003_car_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="condition",
            field=models.CharField(
                choices=[
                    ("Brand New", "Brand New"),
                    ("Foreign Used", "Foreign Used"),
                    ("Local Used", "Local Used"),
                ],
                default="Foreign Used",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="mileage",
            field=models.PositiveIntegerField(
                default=0, help_text="Mileage in kilometers (km)"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="transmission",
            field=models.CharField(
                choices=[("Automatic", "Automatic"), ("Manual", "Manual")],
                default="Automatic",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="year",
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
