# Generated by Django 6.0.5 on 2026-05-14 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0004_carvideo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="carimage",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery",
                to="showroom.car",
            ),
        ),
        migrations.AlterField(
            model_name="carimage",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="carvideo",
            name="video",
            field=models.FileField(upload_to=""),
        ),
    ]
