# Generated by Django 6.0.5 on 2026-05-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0005_alter_car_image_alter_carimage_car_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.ImageField(upload_to="cars/"),
        ),
        migrations.AlterField(
            model_name="carimage",
            name="image",
            field=models.ImageField(upload_to="cars/gallery/"),
        ),
        migrations.AlterField(
            model_name="carvideo",
            name="video",
            field=models.FileField(upload_to="cars/videos/"),
        ),
    ]
