# Generated by Django 6.0.5 on 2026-05-15 10:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0006_alter_car_image_alter_carimage_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
