# Generated by Django 6.0.5 on 2026-05-18 15:31

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0007_alter_car_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="video",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Upload an MP4 car showcase video",
                max_length=255,
                null=True,
                verbose_name="car_videos/",
            ),
        ),
        migrations.AlterField(
            model_name="carimage",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="showroom.car",
            ),
        ),
        migrations.AlterField(
            model_name="carimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="carvideo",
            name="car",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_videos",
                to="showroom.car",
            ),
        ),
        migrations.AlterField(
            model_name="carvideo",
            name="video",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="video"
            ),
        ),
    ]
